#!/usr/bin/env python3
"""
TikTok Collections Monitor

Monitors your TikTok collections for changes, detects new/deleted videos,
and downloads new videos with metadata.

Modes:
  --sync       : Fetch collections and videos, update queue
  --download   : Process download queue
  --watch      : Run sync periodically + process downloads
"""

import argparse
import json
import logging
import os
import subprocess
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path
from typing import Optional

from playwright.sync_api import sync_playwright

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger(__name__)


class DataStore:
    """JSON-based data store for collections, videos, and download queue."""

    def __init__(self, data_dir: str):
        self.data_dir = Path(data_dir)
        self.data_dir.mkdir(parents=True, exist_ok=True)

        self.collections_file = self.data_dir / "collections.json"
        self.videos_file = self.data_dir / "videos.json"
        self.queue_file = self.data_dir / "download_queue.json"
        self.data_js_file = self.data_dir / "data.js"
        self.viewer_file = self.data_dir / "viewer.html"

        self.collections = self._load(self.collections_file, {})
        self.videos = self._load(self.videos_file, {})
        self.queue = self._load(self.queue_file, {"pending": [], "completed": [], "failed": []})

        # Write viewer HTML on startup
        self._write_viewer_html()
        self._write_data_js()

    def _load(self, path: Path, default: dict) -> dict:
        if path.exists():
            try:
                with open(path) as f:
                    content = f.read()
                    if not content.strip():
                        return default
                    return json.loads(content)
            except json.JSONDecodeError:
                logger.warning(f"Corrupted JSON file: {path}, using default")
                return default
        return default

    def _save(self, path: Path, data: dict):
        with open(path, "w") as f:
            json.dump(data, f, indent=2)

    def _write_data_js(self):
        """Write data.js for the static viewer (allows viewing without a server)."""
        content = "// Auto-generated by tiktok_monitor.py - do not edit\n"
        content += f"window.collectionsData = {json.dumps(self.collections)};\n"
        content += f"window.videosData = {json.dumps(self.videos)};\n"
        with open(self.data_js_file, "w") as f:
            f.write(content)

    def _write_viewer_html(self):
        """Write the static viewer HTML file."""
        # Get viewer.html from the same directory as this script
        script_dir = Path(__file__).parent
        viewer_src = script_dir / "viewer.html"
        if viewer_src.exists():
            import shutil
            shutil.copy(viewer_src, self.viewer_file)
            logger.info(f"Viewer written to: {self.viewer_file}")

    def save_collections(self):
        self._save(self.collections_file, self.collections)
        self._write_data_js()

    def save_videos(self):
        self._save(self.videos_file, self.videos)
        self._write_data_js()

    def save_queue(self):
        self._save(self.queue_file, self.queue)

    def update_collection(self, coll_id: str, coll_data: dict):
        self.collections[coll_id] = {
            **coll_data,
            "updated_at": datetime.now().isoformat(),
        }

    def add_video(self, video_id: str, video_data: dict):
        is_new = video_id not in self.videos
        self.videos[video_id] = {
            **video_data,
            "cached_at": datetime.now().isoformat(),
        }
        return is_new

    def queue_download(self, video_id: str, video_data: dict):
        # Don't queue if already in queue or completed
        if video_id in [v["id"] for v in self.queue["pending"]]:
            return False
        if video_id in self.queue["completed"]:
            return False

        self.queue["pending"].append({
            "id": video_id,
            "url": video_data.get("url"),
            "collection": video_data.get("collection_name"),
            "author": video_data.get("author"),
            "desc": video_data.get("desc", ""),
            "queued_at": datetime.now().isoformat(),
        })
        return True

    def get_pending_downloads(self) -> list:
        return self.queue["pending"]

    def mark_downloaded(self, video_id: str, path: str):
        # Remove from pending
        self.queue["pending"] = [v for v in self.queue["pending"] if v["id"] != video_id]
        self.queue["completed"].append(video_id)

        # Update video record
        if video_id in self.videos:
            self.videos[video_id]["downloaded"] = True
            self.videos[video_id]["download_path"] = path
            self.videos[video_id]["downloaded_at"] = datetime.now().isoformat()

    def mark_failed(self, video_id: str, error: str):
        # Move from pending to failed
        for v in self.queue["pending"]:
            if v["id"] == video_id:
                v["error"] = error
                v["failed_at"] = datetime.now().isoformat()
                self.queue["failed"].append(v)
                break
        self.queue["pending"] = [v for v in self.queue["pending"] if v["id"] != video_id]

    def delete_video(self, video_id: str) -> Optional[str]:
        """
        Delete a video from tracking and remove its files.

        Returns the deleted file path if files were removed, None otherwise.
        """
        import shutil

        deleted_path = None

        # Get video info before removing
        video = self.videos.get(video_id)
        if video:
            download_path = video.get("download_path")
            if download_path:
                video_dir = Path(download_path).parent
                if video_dir.exists():
                    shutil.rmtree(video_dir)
                    deleted_path = str(video_dir)

                    # Also remove parent collection folder if empty
                    collection_dir = video_dir.parent
                    if collection_dir.exists() and not any(collection_dir.iterdir()):
                        collection_dir.rmdir()

            # Remove from videos
            del self.videos[video_id]

        # Remove from queue lists
        self.queue["pending"] = [v for v in self.queue["pending"] if v["id"] != video_id]
        self.queue["failed"] = [v for v in self.queue["failed"] if v["id"] != video_id]
        if video_id in self.queue["completed"]:
            self.queue["completed"].remove(video_id)

        return deleted_path

    def clear_all_data(self):
        """Clear all tracking data (collections, videos, queue)."""
        self.collections = {}
        self.videos = {}
        self.queue = {"pending": [], "completed": [], "failed": []}

    def get_downloaded_videos(self) -> list:
        """Get list of all downloaded video IDs."""
        return [vid for vid, data in self.videos.items() if data.get("downloaded")]

    def verify_downloads(self) -> dict:
        """
        Verify download status by checking actual files on disk.
        Returns dict with counts of fixed records.
        """
        fixed_downloaded = 0
        fixed_missing = 0

        for vid_id, vid_data in self.videos.items():
            download_path = vid_data.get("download_path")
            marked_downloaded = vid_data.get("downloaded", False)

            # Check if file actually exists
            file_exists = download_path and Path(download_path).exists()

            if marked_downloaded and not file_exists:
                # Marked as downloaded but file is missing
                vid_data["downloaded"] = False
                vid_data["download_path"] = None
                fixed_missing += 1
            elif not marked_downloaded and file_exists:
                # File exists but not marked as downloaded
                vid_data["downloaded"] = True
                fixed_downloaded += 1

        if fixed_downloaded > 0 or fixed_missing > 0:
            self.save_videos()

        return {"fixed_downloaded": fixed_downloaded, "fixed_missing": fixed_missing}

    def count_actual_downloads(self) -> dict:
        """
        Count actual video files on disk by scanning the download directory.
        Returns dict with collection_name -> count mapping and _total.
        """
        counts = {"_total": 0}

        # Scan all subdirectories (collections) in the data_dir
        for collection_dir in self.data_dir.iterdir():
            if not collection_dir.is_dir():
                continue
            # Skip hidden directories
            if collection_dir.name.startswith("."):
                continue

            collection_count = 0
            # Each collection contains video_id folders
            for video_dir in collection_dir.iterdir():
                if not video_dir.is_dir():
                    continue
                # Check if there's a video file in this folder
                for f in video_dir.iterdir():
                    if f.suffix.lower() in [".mp4", ".webm", ".mkv"]:
                        collection_count += 1
                        counts["_total"] += 1
                        break  # Only count one video per folder

            if collection_count > 0:
                counts[collection_dir.name] = collection_count

        return counts


class TikTokClient:
    """Client for fetching TikTok data via browser automation."""

    def __init__(self, sessionid: str):
        self.sessionid = sessionid

    def _create_context(self, playwright):
        browser = playwright.chromium.launch(headless=True)
        context = browser.new_context(
            user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
            viewport={"width": 1920, "height": 1080},
        )
        context.add_cookies([
            {"name": "sessionid", "value": self.sessionid, "domain": ".tiktok.com", "path": "/"},
            {"name": "sessionid_ss", "value": self.sessionid, "domain": ".tiktok.com", "path": "/"},
        ])
        return browser, context

    def get_collections(self) -> list:
        """Fetch all collections."""
        collections = []

        logger.info("Launching browser to fetch collections...")
        with sync_playwright() as p:
            browser, context = self._create_context(p)
            page = context.new_page()

            def handle_response(response):
                if "collection_list" in response.url:
                    try:
                        data = response.json()
                        if "collectionList" in data:
                            for coll in data["collectionList"]:
                                if not any(c.get("collectionId") == coll.get("collectionId") for c in collections):
                                    collections.append(coll)
                                    logger.info(f"  Found collection: {coll.get('name')} ({coll.get('total', 0)} videos)")
                    except Exception:
                        pass

            page.on("response", handle_response)
            page.goto("https://www.tiktok.com/", wait_until="networkidle", timeout=30000)
            page.wait_for_timeout(3000)
            browser.close()

        return collections

    def get_collection_videos(self, collection_id: str, collection_name: str, limit: Optional[int] = None) -> list:
        """Fetch videos in a collection."""
        videos = []
        seen_ids = set()

        with sync_playwright() as p:
            browser, context = self._create_context(p)
            page = context.new_page()

            def handle_response(response):
                if "collection/item_list" in response.url or "collect/item_list" in response.url:
                    try:
                        data = response.json()
                        if "itemList" in data:
                            new_count = 0
                            for item in data["itemList"]:
                                vid_id = item.get("id")
                                if vid_id and vid_id not in seen_ids:
                                    seen_ids.add(vid_id)
                                    videos.append(item)
                                    new_count += 1
                            if new_count > 0:
                                logger.info(f"    [{collection_name}] Loaded {len(videos)} videos...")
                    except Exception:
                        pass

            page.on("response", handle_response)

            url = f"https://www.tiktok.com/@me/collection/{collection_name}-{collection_id}"
            page.goto(url, wait_until="networkidle", timeout=30000)
            page.wait_for_timeout(3000)

            # Scroll to load ALL videos - keep going until we hit the true bottom
            scroll_count = 0
            max_scrolls = 500  # Enough for ~10,000+ videos
            last_height = 0

            while scroll_count < max_scrolls:
                prev_count = len(videos)

                # Scroll to bottom
                page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
                page.wait_for_timeout(2000)
                scroll_count += 1

                # Check if page height changed (true indicator of more content)
                current_height = page.evaluate("document.body.scrollHeight")

                if len(videos) == prev_count and current_height == last_height:
                    # No new videos AND page didn't grow - try a few more times
                    page.wait_for_timeout(1000)
                    page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
                    page.wait_for_timeout(2000)
                    final_height = page.evaluate("document.body.scrollHeight")

                    if final_height == current_height and len(videos) == prev_count:
                        logger.info(f"    [{collection_name}] Reached bottom at {len(videos)} videos")
                        break

                last_height = current_height

                if limit and len(videos) >= limit:
                    break

            browser.close()

        return videos[:limit] if limit else videos

    def get_favorites(self, limit: Optional[int] = None) -> list:
        """Fetch favorited/liked videos (not in any specific collection)."""
        videos = []

        logger.info("Launching browser to fetch favorites...")
        with sync_playwright() as p:
            browser, context = self._create_context(p)
            page = context.new_page()

            def handle_response(response):
                # TikTok uses various endpoints for favorites/liked videos
                if any(x in response.url for x in ["favorite/item_list", "favorite_item_list", "liked/item_list", "like-list"]):
                    try:
                        data = response.json()
                        if "itemList" in data:
                            videos.extend(data["itemList"])
                            logger.info(f"    [Favorites] Loaded {len(videos)} videos...")
                    except Exception:
                        pass

            page.on("response", handle_response)

            # Navigate to favorites page
            page.goto("https://www.tiktok.com/@me", wait_until="networkidle", timeout=30000)
            page.wait_for_timeout(2000)

            # Try to click on the Favorites tab if it exists
            try:
                # Look for favorites tab - TikTok UI varies but typically has a favorites/liked tab
                favorites_selectors = [
                    'div[data-e2e="favorites-tab"]',
                    'a[href*="favorites"]',
                    'span:has-text("Favorites")',
                    'div:has-text("Favorites"):not(:has(*))',
                ]
                for selector in favorites_selectors:
                    try:
                        if page.locator(selector).count() > 0:
                            page.locator(selector).first.click()
                            page.wait_for_timeout(2000)
                            break
                    except Exception:
                        continue
            except Exception:
                pass

            # Scroll to load more
            scroll_count = 0
            max_scrolls = 50 if not limit else (limit // 30) + 2

            while scroll_count < max_scrolls:
                prev_count = len(videos)
                page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
                page.wait_for_timeout(1500)
                scroll_count += 1

                if len(videos) == prev_count:
                    break
                if limit and len(videos) >= limit:
                    break

            browser.close()

        return videos[:limit] if limit else videos


class VideoDownloader:
    """Downloads TikTok videos using yt-dlp."""

    def __init__(self, download_dir: str, cookies: dict = None, max_workers: int = 10):
        self.download_dir = Path(download_dir)
        self.cookies = cookies or {}
        self.max_workers = max_workers
        self._cookies_files = self._create_cookies_pool()

    def _create_cookies_pool(self) -> list:
        """Create a pool of cookies files, one per worker."""
        if not self.cookies:
            return []

        lines = ["# Netscape HTTP Cookie File", "# https://curl.haxx.se/rfc/cookie_spec.html", ""]
        for name, value in self.cookies.items():
            if value:
                lines.append(f".tiktok.com\tTRUE\t/\tTRUE\t0\t{name}\t{value}")
        content = "\n".join(lines)

        cookies_dir = self.download_dir / ".cookies"
        cookies_dir.mkdir(parents=True, exist_ok=True)
        files = []
        for i in range(self.max_workers):
            path = cookies_dir / f"{i}.txt"
            with open(path, "w") as f:
                f.write(content)
            files.append(path)
        return files

    def download(self, video_id: str, author: str, collection_name: str, description: str = "", worker_id: int = 0) -> Optional[str]:
        """
        Download video into collection/video_id/ folder with metadata.

        Returns the download path on success, None on failure.
        """
        # Create folder structure: collection/video_id/
        safe_collection = "".join(c if c.isalnum() or c in " -_" else "_" for c in collection_name)
        video_dir = self.download_dir / safe_collection / video_id
        video_dir.mkdir(parents=True, exist_ok=True)

        video_url = f"https://www.tiktok.com/@{author}/video/{video_id}"
        output_template = str(video_dir / f"{video_id}.%(ext)s")

        try:
            cmd = [
                sys.executable, "-m", "yt_dlp",
                "--no-warnings",
                "-o", output_template,
                "--write-info-json",
            ]

            # Use worker-specific cookies file from pool
            if self._cookies_files:
                cookies_file = self._cookies_files[worker_id % len(self._cookies_files)]
                cmd.extend(["--cookies", str(cookies_file)])

            cmd.append(video_url)

            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=180,
            )

            if result.returncode == 0:
                # Save description/caption
                if description:
                    with open(video_dir / "caption.txt", "w") as f:
                        f.write(description)

                # Find the downloaded video file
                for ext in ["mp4", "webm", "mkv"]:
                    video_file = video_dir / f"{video_id}.{ext}"
                    if video_file.exists():
                        return str(video_file)

                # Check if any video file exists
                for f in video_dir.iterdir():
                    if f.suffix in [".mp4", ".webm", ".mkv"]:
                        return str(f)
            else:
                logger.error(f"yt-dlp error: {result.stderr[:200]}")

        except subprocess.TimeoutExpired:
            logger.error(f"Download timeout for {video_id}")
        except Exception as e:
            logger.error(f"Download error: {e}")

        return None


def load_config(config_path: str = "config.json") -> dict:
    path = Path(config_path)
    if not path.exists():
        logger.error(f"Config file not found: {config_path}")
        sys.exit(1)
    with open(path) as f:
        return json.load(f)


def _download_collection_videos(store: DataStore, downloader: "VideoDownloader", collection_id: str, max_parallel: int = 10) -> int:
    """Download pending videos for a specific collection with parallel downloads. Returns count of successful downloads."""
    pending = [v for v in store.get_pending_downloads() if v.get("collection") == store.collections.get(collection_id, {}).get("name") or (collection_id == "_favorites" and v.get("collection") == "Favorites")]

    if not pending:
        return 0

    success_count = [0]  # Use list to allow modification in nested scope
    lock = threading.Lock()

    def download_worker(item, index, worker_id):
        """Worker function to download a single video."""
        vid_id = item["id"]
        author = item.get("author", "unknown")
        collection = item.get("collection", "uncategorized")
        desc = item.get("desc", "")

        logger.info(f"    [{index}/{len(pending)}] Downloading {vid_id} (@{author})")

        path = downloader.download(vid_id, author, collection, desc, worker_id=worker_id)

        return {
            "vid_id": vid_id,
            "path": path,
            "success": path is not None,
        }

    with ThreadPoolExecutor(max_workers=max_parallel) as executor:
        future_to_item = {
            executor.submit(download_worker, item, i, i % max_parallel): item
            for i, item in enumerate(pending, 1)
        }

        for future in as_completed(future_to_item):
            result = future.result()
            vid_id = result["vid_id"]

            with lock:
                if result["success"]:
                    store.mark_downloaded(vid_id, result["path"])
                    logger.info(f"      Success: {result['path']}")
                    success_count[0] += 1
                else:
                    store.mark_failed(vid_id, "Download failed")
                    logger.warning(f"      Failed: {vid_id}")

                store.save_queue()
                store.save_videos()

    return success_count[0]


def _process_collection_videos(store: DataStore, coll_id: str, coll_name: str, videos: list) -> tuple:
    """Process fetched videos for a collection. Returns (new_count, queued_count, deleted_count, found_ids)."""
    found_video_ids = set()
    new_count = 0
    queued_count = 0
    deleted_count = 0

    for vid in videos:
        vid_id = vid.get("id")
        if not vid_id:
            continue

        found_video_ids.add(vid_id)
        author = vid.get("author", {}).get("uniqueId", "unknown")
        video_data = {
            "id": vid_id,
            "author": author,
            "desc": vid.get("desc", ""),
            "collection_id": coll_id,
            "collection_name": coll_name,
            "url": f"https://www.tiktok.com/@{author}/video/{vid_id}",
            "create_time": vid.get("createTime"),
            "stats": vid.get("stats", {}),
            "deleted_from_tiktok": False,
        }

        is_new = store.add_video(vid_id, video_data)
        if is_new:
            new_count += 1
            if store.queue_download(vid_id, video_data):
                queued_count += 1

    # Check for videos that were in this collection but are now missing
    for vid_id, vid_data in list(store.videos.items()):
        if vid_data.get("collection_id") == coll_id:
            if vid_id not in found_video_ids and not vid_data.get("deleted_from_tiktok"):
                vid_data["deleted_from_tiktok"] = True
                vid_data["deleted_at"] = datetime.now().isoformat()
                deleted_count += 1
                logger.info(f"  [{coll_name}] Marked as deleted: {vid_id}")

    return new_count, queued_count, deleted_count, found_video_ids


def cmd_sync(client: TikTokClient, store: DataStore, collection_limit: Optional[int] = None, video_limit: Optional[int] = None, downloader: Optional[VideoDownloader] = None, max_parallel: int = 10):
    """Sync collections and videos, queue new downloads. Optionally download after each collection."""
    logger.info("=== SYNC MODE ===")

    # Step 1: Fetch collections
    logger.info("Fetching collections...")
    collections = client.get_collections()
    logger.info(f"Found {len(collections)} collections")

    for coll in collections:
        coll_id = coll.get("collectionId")
        coll_name = coll.get("name", "Unnamed")
        store.update_collection(coll_id, {
            "id": coll_id,
            "name": coll_name,
            "total": coll.get("total", 0),
        })
    store.save_collections()

    # Step 2: Fetch videos for each collection (in parallel)
    collections_to_process = list(store.collections.values())
    if collection_limit:
        collections_to_process = collections_to_process[:collection_limit]

    new_videos = 0
    downloaded = 0
    deleted_count = 0

    logger.info(f"Fetching videos from {len(collections_to_process)} collections (up to {max_parallel} in parallel)...")

    def fetch_worker(coll):
        """Worker function to fetch videos for a collection."""
        coll_id = coll["id"]
        coll_name = coll["name"]
        thread_id = threading.current_thread().name
        logger.info(f"  [{thread_id}] Starting fetch: {coll_name}")
        try:
            videos = client.get_collection_videos(coll_id, coll_name, limit=video_limit)
            logger.info(f"  [{thread_id}] Finished fetch: {coll_name} ({len(videos)} videos)")
            return {"coll_id": coll_id, "coll_name": coll_name, "videos": videos, "error": None}
        except Exception as e:
            logger.error(f"  [{thread_id}] Error fetching {coll_name}: {e}")
            return {"coll_id": coll_id, "coll_name": coll_name, "videos": [], "error": str(e)}

    # Submit all collection fetches to thread pool
    with ThreadPoolExecutor(max_workers=max_parallel) as executor:
        future_to_coll = {executor.submit(fetch_worker, coll): coll for coll in collections_to_process}

        # Process results as they complete
        for future in as_completed(future_to_coll):
            result = future.result()
            coll_id = result["coll_id"]
            coll_name = result["coll_name"]
            videos = result["videos"]

            logger.info(f"  {coll_name}: Found {len(videos)} videos")

            if result["error"]:
                continue

            # Process the fetched videos
            new_count, queued_count, del_count, _ = _process_collection_videos(
                store, coll_id, coll_name, videos
            )
            new_videos += new_count
            deleted_count += del_count

            # Download immediately if downloader is provided
            if downloader and queued_count > 0:
                store.save_videos()
                store.save_queue()
                logger.info(f"  Downloading {queued_count} new videos from {coll_name}...")
                downloaded += _download_collection_videos(store, downloader, coll_id)

    # Step 3: Fetch favorited videos (not in any collection)
    logger.info("Fetching favorited videos (not in collections)...")
    favorites = client.get_favorites(limit=video_limit)
    logger.info(f"Found {len(favorites)} favorited videos")

    # Track which favorites we found
    found_favorite_ids = set()
    favorites_new = 0
    favorites_queued = 0

    for vid in favorites:
        vid_id = vid.get("id")
        if not vid_id:
            continue

        # Skip if this video is already in a collection
        if vid_id in store.videos and store.videos[vid_id].get("collection_id") != "_favorites":
            continue

        found_favorite_ids.add(vid_id)
        author = vid.get("author", {}).get("uniqueId", "unknown")
        video_data = {
            "id": vid_id,
            "author": author,
            "desc": vid.get("desc", ""),
            "collection_id": "_favorites",
            "collection_name": "Favorites",
            "url": f"https://www.tiktok.com/@{author}/video/{vid_id}",
            "create_time": vid.get("createTime"),
            "stats": vid.get("stats", {}),
            "deleted_from_tiktok": False,
        }

        is_new = store.add_video(vid_id, video_data)
        if is_new:
            favorites_new += 1
            new_videos += 1
            if store.queue_download(vid_id, video_data):
                favorites_queued += 1

    # Check for favorites that are now missing
    for vid_id, vid_data in store.videos.items():
        if vid_data.get("collection_id") == "_favorites":
            if vid_id not in found_favorite_ids and not vid_data.get("deleted_from_tiktok"):
                vid_data["deleted_from_tiktok"] = True
                vid_data["deleted_at"] = datetime.now().isoformat()
                deleted_count += 1
                logger.info(f"  Marked favorite as deleted: {vid_id}")

    if favorites_new > 0:
        logger.info(f"  New favorites: {favorites_new}, queued: {favorites_queued}")

    # Download favorites immediately if downloader is provided
    if downloader and favorites_queued > 0:
        store.save_videos()
        store.save_queue()
        logger.info(f"  Downloading {favorites_queued} new favorites...")
        downloaded += _download_collection_videos(store, downloader, "_favorites")

    store.save_videos()
    store.save_queue()

    logger.info("=== SYNC COMPLETE ===")
    logger.info(f"New videos found: {new_videos}")
    logger.info(f"Downloaded: {downloaded}")
    logger.info(f"Marked as deleted from TikTok: {deleted_count}")
    logger.info(f"Pending downloads: {len(store.get_pending_downloads())}")


def cmd_download(store: DataStore, downloader: VideoDownloader, limit: Optional[int] = None, max_parallel: int = 10):
    """Process download queue with parallel downloads."""
    logger.info("=== DOWNLOAD MODE ===")

    pending = store.get_pending_downloads()
    if not pending:
        logger.info("No pending downloads.")
        return

    to_process = pending[:limit] if limit else pending
    logger.info(f"Processing {len(to_process)} downloads (up to {max_parallel} in parallel)...")

    success_count = 0
    fail_count = 0
    lock = threading.Lock()

    def download_worker(item, index, worker_id):
        """Worker function to download a single video."""
        vid_id = item["id"]
        author = item.get("author", "unknown")
        collection = item.get("collection", "uncategorized")
        desc = item.get("desc", "")

        logger.info(f"[{index}/{len(to_process)}] Downloading {vid_id} from {collection} (@{author})")

        path = downloader.download(vid_id, author, collection, desc, worker_id=worker_id)

        return {
            "vid_id": vid_id,
            "path": path,
            "success": path is not None,
        }

    with ThreadPoolExecutor(max_workers=max_parallel) as executor:
        # Submit all downloads
        future_to_item = {
            executor.submit(download_worker, item, i, i % max_parallel): item
            for i, item in enumerate(to_process, 1)
        }

        # Process results as they complete
        for future in as_completed(future_to_item):
            result = future.result()
            vid_id = result["vid_id"]

            with lock:
                if result["success"]:
                    store.mark_downloaded(vid_id, result["path"])
                    logger.info(f"  Success: {result['path']}")
                    success_count += 1
                else:
                    store.mark_failed(vid_id, "Download failed")
                    logger.warning(f"  Failed: {vid_id}")
                    fail_count += 1

                store.save_queue()
                store.save_videos()

    logger.info("=== DOWNLOAD COMPLETE ===")
    logger.info(f"Downloaded: {success_count}, Failed: {fail_count}")
    logger.info(f"Remaining in queue: {len(store.get_pending_downloads())}")


def cmd_watch(client: TikTokClient, store: DataStore, downloader: VideoDownloader, interval: int):
    """Watch mode: periodic sync + download."""
    logger.info(f"=== WATCH MODE (every {interval} minutes) ===")
    logger.info("Press Ctrl+C to stop")
    logger.info(f"Current status: {len(store.videos)} videos tracked, {len(store.queue['pending'])} pending")

    while True:
        try:
            logger.info("Starting sync cycle...")

            # Sync and download - downloads happen after each collection
            cmd_sync(client, store, downloader=downloader)

            # Process any remaining downloads (e.g., from previous failed attempts)
            cmd_download(store, downloader)

            logger.info(f"Next check in {interval} minutes...")
            time.sleep(interval * 60)

        except KeyboardInterrupt:
            logger.info("Stopping...")
            break
        except Exception as e:
            logger.error(f"Error: {e}")
            logger.info(f"Retrying in {interval} minutes...")
            time.sleep(interval * 60)


def cmd_delete(store: DataStore, video_ids: list, delete_all: bool = False):
    """Delete videos and their files."""
    import shutil

    logger.info("=== DELETE MODE ===")

    if delete_all:
        # Get all video IDs (not just downloaded)
        video_ids = list(store.videos.keys())
        if not video_ids and not store.collections:
            logger.info("No data to delete.")
            return
        logger.info(f"Deleting all data ({len(video_ids)} videos, {len(store.collections)} collections)...")

        # Delete all video folders
        deleted = 0
        for vid_id in video_ids:
            path = store.delete_video(vid_id)
            if path:
                deleted += 1

        # Clean up any remaining collection folders in the download directory
        for item in store.data_dir.iterdir():
            if item.is_dir() and item.name not in [".", ".."]:
                # Skip if it's not a collection folder (check if it contains video folders)
                try:
                    shutil.rmtree(item)
                    logger.info(f"  Removed folder: {item.name}")
                except Exception:
                    pass

        # Clear all tracking data
        store.clear_all_data()
        store.save_collections()
        store.save_videos()
        store.save_queue()

        logger.info("=== DELETE COMPLETE ===")
        logger.info(f"Deleted {deleted} video(s) and all tracking data")
        return

    elif not video_ids:
        logger.info("No video IDs specified. Use --delete <id> or --delete-all")
        return

    deleted = 0
    for vid_id in video_ids:
        path = store.delete_video(vid_id)
        if path:
            logger.info(f"  Deleted: {vid_id} ({path})")
            deleted += 1
        else:
            logger.info(f"  Removed from tracking: {vid_id}")

    store.save_videos()
    store.save_queue()

    logger.info("=== DELETE COMPLETE ===")
    logger.info(f"Deleted {deleted} video(s) and files")


def cmd_status(store: DataStore):
    """Show current status."""
    # Verify downloads against actual files on disk
    logger.info("Verifying downloads against disk...")
    verify_result = store.verify_downloads()
    if verify_result["fixed_downloaded"] > 0 or verify_result["fixed_missing"] > 0:
        logger.info(f"  Fixed {verify_result['fixed_downloaded']} unmarked downloads, {verify_result['fixed_missing']} missing files")

    # Get actual download counts from disk
    actual_counts = store.count_actual_downloads()

    deleted_videos = [v for v in store.videos.values() if v.get("deleted_from_tiktok")]

    logger.info("=== STATUS ===")
    logger.info(f"Collections: {len(store.collections)}")
    logger.info(f"Videos tracked: {len(store.videos)}")
    logger.info(f"Actually downloaded (verified): {actual_counts['_total']}")
    logger.info(f"Deleted from TikTok: {len(deleted_videos)}")
    logger.info(f"Pending downloads: {len(store.queue['pending'])}")
    logger.info(f"Failed downloads: {len(store.queue['failed'])}")

    # Show download state summary by collection
    if store.collections:
        logger.info("--- Collections Overview ---")
        for coll_id, coll in store.collections.items():
            coll_name = coll.get("name", "Unknown")
            # Count videos in this collection
            coll_videos = [v for v in store.videos.values() if v.get("collection_id") == coll_id]
            # Get folder name (sanitized version of collection name)
            safe_name = "".join(c if c.isalnum() or c in " -_" else "_" for c in coll_name)
            downloaded = actual_counts.get(safe_name, 0)  # Use folder name for disk count
            deleted = sum(1 for v in coll_videos if v.get("deleted_from_tiktok"))
            total = len(coll_videos)
            status = f"{downloaded}/{total} downloaded"
            if deleted:
                status += f", {deleted} deleted"
            logger.info(f"  {coll_name}: {status}")

    if deleted_videos:
        logger.info("--- Deleted from TikTok ---")
        for vid in deleted_videos[:10]:
            vid_id = vid.get("id", "unknown")
            coll_name = vid.get("collection_name", "unknown")
            downloaded = "saved" if vid.get("downloaded") else "NOT saved"
            logger.info(f"  [{coll_name}] {vid_id} - {downloaded}")
        if len(deleted_videos) > 10:
            logger.info(f"  ... and {len(deleted_videos) - 10} more")

    if store.queue["pending"]:
        logger.info("--- Pending Downloads ---")
        for item in store.queue["pending"][:10]:
            logger.info(f"  [{item['collection']}] {item['id']}")
        if len(store.queue["pending"]) > 10:
            logger.info(f"  ... and {len(store.queue['pending']) - 10} more")

    if store.queue["failed"]:
        logger.info("--- Failed Downloads ---")
        for item in store.queue["failed"][:5]:
            error = item.get("error", "Unknown error")
            logger.info(f"  [{item['collection']}] {item['id']} - {error}")
        if len(store.queue["failed"]) > 5:
            logger.info(f"  ... and {len(store.queue['failed']) - 5} more")


def main():
    parser = argparse.ArgumentParser(description="TikTok Collections Monitor")
    parser.add_argument("--sync", action="store_true", help="Fetch collections and videos, update queue")
    parser.add_argument("--download", action="store_true", help="Process download queue")
    parser.add_argument("--watch", action="store_true", help="Run sync + download periodically")
    parser.add_argument("--status", action="store_true", help="Show current status")
    parser.add_argument("--interval", "-i", type=int, default=60, help="Watch interval in minutes")
    parser.add_argument("--limit", "-l", type=int, help="Limit downloads per run")
    parser.add_argument("--collection-limit", type=int, help="Limit collections to sync")
    parser.add_argument("--video-limit", type=int, help="Limit videos per collection")
    parser.add_argument("--delete", nargs="+", metavar="VIDEO_ID", help="Delete specific video(s) by ID")
    parser.add_argument("--delete-all", action="store_true", help="Delete all downloaded videos")
    args = parser.parse_args()

    logger.info("TikTok Collections Monitor")
    logger.info("-" * 40)

    config = load_config()
    sessionid = config.get("cookies", {}).get("sessionid", "")
    if not sessionid:
        logger.error("No sessionid found in config.json")
        sys.exit(1)

    # Environment variable overrides config (useful for Docker)
    download_dir = os.environ.get("DOWNLOAD_DIR") or config.get("download_dir", "./downloads")

    # Initialize
    client = TikTokClient(sessionid)
    store = DataStore(download_dir)
    cookies = config.get("cookies", {})
    downloader = VideoDownloader(download_dir, cookies)

    logger.info(f"Data/Download dir: {download_dir}")

    if args.status:
        cmd_status(store)
    elif args.delete or args.delete_all:
        cmd_delete(store, args.delete or [], args.delete_all)
    elif args.sync:
        cmd_sync(client, store, args.collection_limit, args.video_limit)
    elif args.download:
        cmd_download(store, downloader, args.limit)
    elif args.watch:
        cmd_watch(client, store, downloader, args.interval)
    else:
        # Default: sync then download
        cmd_sync(client, store, args.collection_limit, args.video_limit)
        cmd_download(store, downloader, args.limit)


if __name__ == "__main__":
    main()
